name: 'Reports'
main: 'com.orangecheese.reports.ReportsPlugin'
version: '1.2'
api-version: '1.20'
commands:
  report:
    description: 'Create a new report'
  reports:
    description: 'Administrative options to manage reports and the plugin settings'